### PR TITLE
Update builscript repository

### PR DESCRIPTION
**Pull request by ghost**
'com.android.tools.build:gradle:2.2.2' is not available in mavencentral, but in jcenter.

### CODE REVIEW

**Comment by wistein** [comment]
Here it works as it is with mavencentral only.
Maybe you should update your environment.
See http://stackoverflow.com/questions/40826935/could-not-find-com-android-tools-buildgradle2-2-2
No need for jcenter() repository.

**Comment by ghost** [comment]
It is not in central, just click on https://repo1.maven.org/maven2/com/android/tools/build/gradle/2.2.2/gradle-2.2.2.pom and it will 404. As you can see in the linked stackoverflow question, the accepted solution is to reference jcenter. You most likely dont need this because you get it either from a local repository (.m2 cache, googles repo etc.) or android studio works around that.

**Comment by wistein** [comment]
Thank you for your support and excuse my wrong assupmtion.
In the meantime I compiled it with jcenter() only and the resulting apk is slightly smaller than before.
So I accept your proposal. The same would be with the other app: TransektCount.

**Comment by ghost** [comment]
Thanks :)

**Pull request merged**
